name: ci 
on:
  push
permissions:
  contents: read
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1

      - name: Setup Go
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # 3.3.1
        with:
          version: v1.50

      - name: Run tests
        run: go test -coverpkg=./... -race -covermode=atomic ./...
